name: Deploy FastAPI to Heroku

on:
  push:
    branches:
      - main  # Trigger on push to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Heroku authentication using API key
      - name: Authenticate with Heroku
        run: |
          echo "machine api.heroku.com" > ~/.netrc
          echo "login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
          echo "password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 5: Deploy to Heroku
      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/ai-assignment.git
          git push heroku main  
      # Push the app to Heroku

      # Step 6: Confirm successful deployment
      - name: Deployment Successful
        run: echo "FastAPI app deployed to Heroku!"
